SET ANSI_PADDING OFF
GO

USE [AdventureWorksDW2012]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EmailDL](
	[EDLCode] [int] IDENTITY(1,1) NOT NULL,
	[EDLSSIS] [VARCHAR](255) NOT NULL,
	[EDLProfile] [VARCHAR](255) NOT NULL,
	[EDLTo] [VARCHAR](2000) NOT NULL,
	[EDLCc] [VARCHAR](2000) NULL,
	[EDLCco] [VARCHAR](2000) NULL,
 CONSTRAINT [PK_EmailDL] PRIMARY KEY CLUSTERED 
(
	[EDLCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

